# La línea 'version' ha sido eliminada por ser obsoleta.

services:
  # --- SERVICIOS DE MONITOREO ---
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./infra/loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml -validation.allow-structured-metadata=false
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Arm1833a
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./logs:/var/log/app
      - ./infra/promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - monitoring

  # --- SERVICIOS DE ANÁLISIS DE CÓDIGO ---
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped
    networks:
      - monitoring

  code-analyzer:
    build:
      context: .
      dockerfile: infra/analysis/Dockerfile
    container_name: code-analyzer
    depends_on:
      - sonarqube
    volumes:
      - .:/usr/src
    networks:
      - monitoring
    environment:
      - SONAR_TOKEN=${SONAR_TOKEN}

volumes:
  loki_data:
  grafana_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  monitoring:
    driver: bridge
